export const SET_BUN = 'SET_BUN';
export const CLEAR_BUN = 'CLEAR_BUN';

export const TOPUP_CONSTRUCTOR_LIST = 'TOPUP_CONSTRUCTOR_LIST';
export const REJECT_CONSTRUCTOR_LIST = 'REJECT_CONSTRUCTOR_LIST';
export const CLEAR_CONSTRUCTOR_LIST = 'CLEAR_CONSTRUCTOR_LIST';

export const UPDATE_CONSTRUCTOR = "UPDATE_CONSTRUCTOR";


export const SET_COST = 'SET_COST';
export const CLEAR_COST = 'CLEAR_COST';
